### ISSUE TITLE
Compile errors when using clang

### ISSUE THREAD

**Issue by npm-sdr** [Opendigitalradio/dablin#29]
Hi,

I have been able to compile and run dablin on macOS but I had to include a couple of standard header files. Would you be able to include the headers below to tools.h on the master branch?

#include <string>

Many thanks,
Niro.

**Comment by basicmaster** [comment]
Hi Niro,

interesting that further headers are required. However in your message I can only see `#include` but no header file names. Could you please check?
Please note that changes are first applied to the `next` branch, before sometime all changes are also pushed to `master`.

Regards,
Stefan

**Comment by russel** [comment]
The email of the issue gave:
```c++
#include <iostream>
#include <sstream>
#include <string>
```

**Comment by russel** [comment]
I just tried building with Clang-5.0 on Debian Sid and there are problems with the tools.cc compilation and linking. I do not have an immediate fix just now and probably can't get back to this till tomorrow afternoon.

**Comment by npm-sdr** [comment]
Hi Stefan,

Sorry it was my mistake, I only needed #include <string>. Other 2 headers
aren't necessary.

I also have a link issue with libmpg123 on macOS since upgrading to macOS
High Sierra (macOS 10.13) then updating mpg123 to the latest from the
package manager. The cmake files don't seem to pass the absolute path
of libmpg123.dylib
from package search results to the linker, causing the link to fail. On
macOS, the mpg123 and most other user installed libs are installed to
/usr/local/lib and pkg-config correctly returns the paths. Normally,
/usr/local/lib
is not in Clang's default library search path list. In the past I worked
around this by creating a softlink to /usr/local/lib/libmpg123.dylib at
/usr/lib/ but this no longer works as /usr/lib/ is not writable (even with
sudo) due to Apple's new System Integrity Protection. Just to get
dablin_gtk to build, I had temporarily hack CMakeLists.txt and add
/usr/local/lib
to library search path list. Not sure where to seek help for this libmpg123
issue.

On a related note, I also changed the c standard compiler option from
-std=c++0x to -std=c++14 as some of the headers (like glibmm) are
generating warnings when using clang-v9.0.0 as those headers already
started using c++14 extensions.

With the header file change and libmpg123 workaround, DABlin works a treat
on macOS again, streaming I/Q from my own SDR, demodulating and generating
an ETI stream to DABlin and playing Union Jack radio.

Kind regards,
Niro.

**Comment by basicmaster** [comment]
Hi Niro,

actually it turned out that there were few locations where `#include <string>` was missing, so I fixed also other files. So this issue should be solved.

Regarding your custom build libmpg123: Do I get you right that `pkg-config --libs libmpg123` also returns `-L/usr/local/lib`? In this case it could be an issue in DABlin's CMake files that I have to check then.

Great that this tool chain works for you! I am curious how DABlin looks like on Mac and if the proportions are right. Could you post a screenshot?

Regards,
Stefan

**Comment by basicmaster** [comment]
@russel Does this commit also fix your build problems under Debian Sid?

**Comment by npm-sdr** [comment]
Hi Stefan,

Many thanks for fixing the missing includes. pkg-config --libs libmpg123
returns the following:

-L/usr/local/Cellar/mpg123/1.25.7/lib -lmpg123

However, the package manager(s) still create softlinks in /usr/local/ to
the actual paths but I'm guessing this is for historical reasons to keep
old makefiles that still don't use pkg-config happy.

I've attached a few screenshots of DABlin on Mac.

Regards,
Niro.

**Comment by russel** [comment]
I now get a build with Clang 5.0. I am wondering whether to try 3.9 and 4.0?

Clang is warning about a C++14 feature being used, is the based version C++14 or is C++11 intended?

**Comment by npm-sdr** [comment]
Hi Russel,

Only warning I get when -std=c++0x is:

/usr/local/Cellar/glibmm/2.54.1/include/glibmm-2.4/glibmm/variant.h:2132:3:
warning: use of this statement in a constexpr function is a C++14 extension
[-Wc++14-extensions]
  (void)arg;
  ^

This is from the function below:

  // swallows any argument

  template <class T>

  constexpr int any_arg(T&& arg)

  {

    (void)arg;

    return 0;

  }

The version of clang is:
  $ clang --version
  Apple LLVM version 9.0.0 (clang-900.0.38)
  Target: x86_64-apple-darwin17.0.0
  Thread model: posix

I don't know much about the level of c++11 features made to clang-3.9/4.0,
whether those compilers even supported constexpr. If those compiler
versions are pre-c++11, is there much point in trying to support them?

Regards,
Niro.

**Comment by basicmaster** [comment]
@russel:
DABlin is currently intended for C++11. Do you get warnings for gtkmm only or also for DABlin?

@npm-sdr:
I compiled with a custom libmpg123 under Ubuntu 16.04 and had no problems. I also have no Mac, so I unfortunately cannot help you with this other issue.

**Comment by basicmaster** [comment]
Posting the DABlin screenshots unfortunately did not work out, because GitHub seems to remove attached pictures when answering an issue via e-mail.

**Comment by npm-sdr** [comment]
I've attached the screenshots to the thread.

Regards,
Niro.

![screen shot 2017-11-14 at 22 07 35_scaled](https://user-images.githubusercontent.com/33637299/32858015-dbd510f8-ca41-11e7-9955-7abc21e3fcf3.png)
<img width="836" alt="screen shot 2017-11-14 at 22 08 42" src="https://user-images.githubusercontent.com/33637299/32858020-e0f5d040-ca41-11e7-8256-18b4c9c88993.png">
<img width="828" alt="screen shot 2017-11-14 at 22 17 30" src="https://user-images.githubusercontent.com/33637299/32858025-e3f9f708-ca41-11e7-9dc3-35ff7c8b4f7e.png">

**Comment by npm-sdr** [comment]
Hi Russel,

I only get 1 warning and that is from glibmm. No warnings in DABlin source
code.

Regarding libmpg123, does it still work if you choose to install libmpg123
libs in a custom directory? I think that's what happens on OSX. Libs get
installed to somewhere and the pkg-config .pc files points to the custom
directory. If a make file doesn't use -L path returned by pkg-config --lib
mpg123, the linker won't be able to find it. AFAIK Xcode's default search
paths don't include /usr/local/{include,lib}

Regards,
Niro.

**Comment by basicmaster** [comment]
Thanks for the screenshots. Interestingly the volume bar icon is missing on Mac, and the label font seems to be a bit small.

I just tried myself with a custom lib dir and ran into the same problem. Indeed it was a bug in the CMake files that did not consider non-standard library paths. So with the fixed `next` branch, building should work for you. Please check and close the issue, if it works (I hope so).

**Comment by npm-sdr** [comment]
DABLin now builds successfully on macOS (High Sierra v10.13) so closing the issue.

Many thanks,
Niro.
